[phases.setup]
nixPkgs = ["python310", "gcc"]
aptPkgs = ["libgl1-mesa-glx", "libgl1", "libglib2.0-0", "libsm6", "libxext6", "libxrender1"]

[phases.install]
cmds = ["python -m venv /opt/venv && /opt/venv/bin/pip install --upgrade pip && /opt/venv/bin/pip install -r requirements.txt"]